name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extend space
        uses: ./.github/actions/extend-space

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - uses: cachix/cachix-action@v10
        with:
          name: holochain-ci

      - name: Test app template
        run: |
          nix develop --command bash -c "sh run_test_app.sh"

      - name: Test module template
        run: |
          nix develop --command bash -c "sh run_test_module.sh"

